package com.xworkz.food_recipe.constants;

public enum SortUsers {
    USERIDASC,USERIDDESC,FIRSTNAMEASC,FIRSTNAMEDESC,LASTNAMEASC,LASTNAMEDESC,EMAILASC,EMAILDESC,
    CONTACTNOASC,CONTACTNODESC,ALTNOASC,ALTNODESC,GENDERASC,GENDERDESC,ADDRESSASC,ADDRESSDESC;
}
